language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - TESTER_PHP_BIN="php-cgi"

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s -c ./tests/travisPhp.ini ./tests

before_script:
  - composer install
